### ISSUE TITLE
harvester: keepitup-worker startup fails on reboot

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#226]

**Comment by AiyionPrime** [comment]
Können bestätigen, das Problem exisiert noch.

**Comment by 1977er** [comment]
```
Jul 30 14:49:10 harvester python[22521]: Traceback (most recent call last):
Jul 30 14:49:10 harvester python[22521]:   File "/opt/keepitup/venv/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
Jul 30 14:49:10 harvester python[22521]:     timeout=timeout
Jul 30 14:49:10 harvester python[22521]:   File "/opt/keepitup/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 756, in urlopen
Jul 30 14:49:10 harvester python[22521]:     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
Jul 30 14:49:10 harvester python[22521]:   File "/opt/keepitup/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 573, in increment
Jul 30 14:49:10 harvester python[22521]:     raise MaxRetryError(_pool, url, error or ResponseError(cause))
Jul 30 14:49:10 harvester python[22521]: urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='harvester.ffh.zone', port=443): Max retries exceeded with url: /api/nodes.json
```

**Comment by 1977er** [comment]
It seems nginx choked on an invalid dns server address. (We used the HE authoritative server instead of their resolver.) Additionally we added a `After=` and `Wants=` line for nginx in the unit file.

**Comment by AiyionPrime** [comment]
@lemoer this is not persistent, as there is no role (#221)
