### ISSUE TITLE
mesh_announce: fails to run on fresh installation

### ISSUE THREAD

**Issue by 1977er** [freifunkh/ansible#52]
Fails with:
```
[root@sn07]:/lib/systemd/system # /opt/mesh-announce/respondd.py -d /opt/mesh-announce -i bat0 -i mesh_fastd -b bat0
Traceback (most recent call last):
  File "/opt/mesh-announce/respondd.py", line 70, in <module>
    get_handler(get_providers(args.directory), {'batadv_dev': args.batadv_iface, 'mesh_ipv4': args.mesh_ipv4})
  File "/opt/mesh-announce/providers/__init__.py", line 153, in get_providers
    provider = Provider.from_directory(directory, dir)
  File "/opt/mesh-announce/providers/__init__.py", line 121, in from_directory
    src = Source.from_file([dirname] + path[0] + [fname], path[0] + [fname])
  File "/opt/mesh-announce/providers/__init__.py", line 88, in from_file
    module = import_module(relpath, __package__)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'providers.providers'
```

**Comment by 1977er** [comment]
Newer version of mesh_announce changed the -d argument.
`-d /opt/mesh-announce` has to be `-d /opt/mesh-announce/providers`
